version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build/

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
#  BeforeInstall:
#    - location: /home/ubuntu/build/stop.sh
#      runas: root
  ApplicationStart:
    - location: start.sh
      runas: root